### ISSUE TITLE
Dreame L10 Pro - Sensor time left is missing

### ISSUE THREAD

**Issue by auanasgheps** [pooyashahidi/xiaomi_vacuum#14]
Hi,
Thanks for making this integration. It's the only one that really supports Dreame robots.

My Dreame L10 Pro (dreame.vacuum.p2029) works fine, but it's missing the "Sensor" clean time left value. All other consumables are reported, but this one is missing.

Here's what the integration reports. Is there anything specific I could do?

```yaml
fan_speed_list:
  - silent
  - standard
  - strong
  - turbo
battery_level: 100
battery_icon: mdi:battery
fan_speed: standard
status: idle
waterbox: removed
operation_status: completed
operating_mode: sleep
error: no error
carpet_boost: true
multi_map_enabled: false
dnd_enabled: true
dnd_start: '22:00'
dnd_stop: '10:00'
audio_volume: 51
audio_language: IT
timezone: Europe/Rome
main_brush_time_left: 298
main_brush_life_percent: 99
side_brush_time_left: 198
side_brush_life_percent: 99
filter_life_percent: 98
filter_time_left: 148
cleaning_area: 2
cleaning_time: 4
first_time_cleaning: '2021-11-24 18:23:32'
total_cleaning_time: 99
total_cleaning_count: 5
total_cleaning_area: 94
clean_cloth_tip: 30
serial_number: blablabla
water_level: medium
water_level_list:
  - low
  - medium
  - high
map_id_list: {}
room_list: {}
friendly_name: Giggino
supported_features: 12924
```
