### ISSUE TITLE
Room configuration

### ISSUE THREAD

**Issue by straff2002** [pooyashahidi/xiaomi_vacuum#3]
Awesome stuff @pooyashahidi , I have a bit of a challenge setting the rooms up. Do I need the service added (where?), or will just the action do? 

I got the rooms from the attributes, and not sure how to set it up as it's continually saving it like this:
actions:
  - name: Clean lounge
    icon: mdi:sofa
    service: xiaomi_vacuum.vacuum_clean_room_by_id
    service_data: null
    entity_id: vacuum.dreame_d9
    rooms:
      - A
      - M
      - P
      - J
    repeats: 1
    clean_mode: 3
    mop_mode: 2

I've tried;

- name: Clean lounge
    icon: mdi:sofa
    service: xiaomi_vacuum.vacuum_clean_room_by_id
    service_data: null
    entity_id: vacuum.dreame_d9
    rooms: [[ 'A'], [ 'M'], [ 'P'], [ 'J']]
    repeats: 1
    clean_mode: 3
    mop_mode: 2

and

- name: Clean lounge
    icon: mdi:sofa
    service: xiaomi_vacuum.vacuum_clean_room_by_id
    service_data: null
    entity_id: vacuum.dreame_d9
    rooms:
      - 'A'
      - 'M'
      - 'P'
      - 'J'
    repeats: 1
    clean_mode: 3
    mop_mode: 2

This doesn't work either and I always get this error:
_Failed to call service xiaomi_vacuum/vacuum_clean_room_by_id. required key not provided @ data['rooms']_
Then I go back to the edit mode and it shows as the first config again. Any ideas?

**Comment by pooyashahidi** [comment]
You can call the service like this to specify multiple rooms:
```yaml
service: xiaomi_vacuum.vacuum_clean_room_by_id
data:
  entity_id: vacuum.dreame_d9
  rooms:
   - A
   - B
   - C
  repeats: 2
  clean_mode: 1
  mop_mode: 3

```
Or like this:

```yaml
service: xiaomi_vacuum.vacuum_clean_room_by_id
data:
  entity_id: vacuum.dreame_d9
  rooms: [A, B, C]
  repeats: 2
  clean_mode: 1
  mop_mode: 3
```

**Comment by straff2002** [comment]
Cheers, do I add the service in the vacuum card?

**Comment by pooyashahidi** [comment]
You can add it where ever you want but if you want to add it in the vacuum card you have to specify the data as `service_data` and not `data`


I created a script in HA for myself like this:
```yaml
alias: clean_room
variables:
  rooms: []
  repeats: 2
  clean_mode: >
    {{state_attr('vacuum.dreame_d9','fan_speed_list').index(state_attr('vacuum.dreame_d9','fan_speed'))
        | int + 0 }}
  mop_mode: >
    {{state_attr('vacuum.dreame_d9','water_level_list').index(state_attr('vacuum.dreame_d9','water_level'))
        | int + 1 }}
sequence:
  - service: xiaomi_vacuum.vacuum_clean_room_by_id
    data:
      entity_id: vacuum.dreame_d9
      rooms: '{{rooms}}'
      repeats: '{{repeats}}'
      clean_mode: '{{clean_mode}}'
      mop_mode: '{{mop_mode}}'
mode: single
```

and then call it like this from the vacuum card:

```yaml
   ...
    actions:
      - name: Clean Bedroom
        icon: svg:bedroom
        service: script.clean_room
        service_data:
          rooms: B
          repeats: 3
      - name: Clean Living Room
        icon: svg:living-room
        service: script.clean_room
        service_data:
          rooms: E
  ...
```

This way I only have to specify the rooms property in the card yaml and it will use the currently selected speed and water level for cleaning.
